# pull the official docker image
FROM python:3.11-rc-slim

# set work directory
WORKDIR /code

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# copy pdf file
COPY ./API_instruction.pdf /code/API_instruction.pdf

# copy project
COPY ./app /code/app

# run command 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]